import { useEffect, useMemo, useState } from "react";
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { BarChart3, Building2, FolderKanban, Inbox, LifeBuoy, LogOut, Receipt } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { supabase } from "@/integrations/supabase/client";
import { pageMeta } from "@/lib/seo";
import type { Database } from "@/integrations/supabase/types";

type Inquiry=Database["public"]["Tables"]["inquiries"]["Row"];type Client=Database["public"]["Tables"]["clients"]["Row"];type Project=Database["public"]["Tables"]["projects"]["Row"];type Ticket=Database["public"]["Tables"]["tickets"]["Row"];type Invoice=Database["public"]["Tables"]["invoices"]["Row"];type Tab="inquiries"|"clients"|"projects"|"tickets"|"invoices"|"analytics";
export const Route=createFileRoute("/_authenticated/admin")({head:()=>pageMeta("Admin workspace","Manage TENURE AI inquiries, clients, projects, and operations."),component:Admin});
function Admin(){const navigate=useNavigate();const {user}=Route.useRouteContext();const [tab,setTab]=useState<Tab>("inquiries");const [loading,setLoading]=useState(true);const [denied,setDenied]=useState(false);const [notice,setNotice]=useState("");const [inquiries,setInquiries]=useState<Inquiry[]>([]);const [clients,setClients]=useState<Client[]>([]);const [projects,setProjects]=useState<Project[]>([]);const [tickets,setTickets]=useState<Ticket[]>([]);const [invoices,setInvoices]=useState<Invoice[]>([]);
async function load(){setLoading(true);const {data:role}=await supabase.from("user_roles").select("role").eq("user_id",user.id).eq("role","admin").maybeSingle();if(!role){setDenied(true);setLoading(false);return;}const [iq,c,p,t,i]=await Promise.all([supabase.from("inquiries").select("*").order("created_at",{ascending:false}),supabase.from("clients").select("*").order("created_at",{ascending:false}),supabase.from("projects").select("*").order("created_at",{ascending:false}),supabase.from("tickets").select("*").order("created_at",{ascending:false}),supabase.from("invoices").select("*").order("created_at",{ascending:false})]);setInquiries(iq.data??[]);setClients(c.data??[]);setProjects(p.data??[]);setTickets(t.data??[]);setInvoices(i.data??[]);setLoading(false)}useEffect(()=>{void load()},[]);
async function status(table:"inquiries"|"projects"|"tickets"|"invoices",id:string,value:string){let error: { message: string } | null = null;if(table==="inquiries")({error}=await supabase.from("inquiries").update({status:value as Inquiry["status"]}).eq("id",id));if(table==="projects")({error}=await supabase.from("projects").update({status:value as Project["status"]}).eq("id",id));if(table==="tickets")({error}=await supabase.from("tickets").update({status:value as Ticket["status"]}).eq("id",id));if(table==="invoices")({error}=await supabase.from("invoices").update({status:value as Invoice["status"]}).eq("id",id));setNotice(error?error.message:"Status updated.");if(!error)await load()}
async function createProject(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const name=String(fd.get("name")??"").trim().replace(/[<>]/g,"").slice(0,120);const summary=String(fd.get("summary")??"").trim().replace(/[<>]/g,"").slice(0,1000);const client_id=String(fd.get("client_id")??"");const service=String(fd.get("service")??"").replace(/[<>]/g,"").slice(0,100);const {error}=await supabase.from("projects").insert({name,summary,client_id,service});setNotice(error?error.message:"Project created.");if(!error){(e.currentTarget as HTMLFormElement).reset();await load()}}
const revenue=useMemo(()=>invoices.filter(i=>i.status==="paid").reduce((s,i)=>s+i.amount_cents,0),[invoices]);const tabs:[Tab,string,typeof Inbox][]=[["inquiries","Inquiries",Inbox],["clients","Clients",Building2],["projects","Projects",FolderKanban],["tickets","Tickets",LifeBuoy],["invoices","Invoices",Receipt],["analytics","Analytics",BarChart3]];
if(denied)return <section className="mx-auto max-w-xl px-5 py-24 text-center"><h1 className="font-display text-5xl">Admin access required</h1><p className="mt-4 text-muted-foreground">This workspace is restricted by your account role and database permissions.</p><Button className="mt-7" asChild><Link to="/dashboard">Go to client workspace</Link></Button></section>;
return <div className="min-h-[calc(100vh-72px)] bg-muted/50"><div className="mx-auto grid max-w-[1500px] md:grid-cols-[230px_1fr]"><aside className="border-b border-border p-5 md:min-h-[calc(100vh-72px)] md:border-b-0 md:border-r"><p className="text-xs font-bold uppercase text-accent">Admin workspace</p><div className="mt-6 flex gap-2 overflow-x-auto md:flex-col">{tabs.map(([id,label,Icon])=><Button key={id} variant={tab===id?"secondary":"ghost"} className="justify-start" onClick={()=>setTab(id)}><Icon/>{label}</Button>)}</div><Button variant="ghost" className="mt-6 justify-start" onClick={async()=>{await supabase.auth.signOut();await navigate({to:"/auth"})}}><LogOut/>Sign out</Button></aside><section className="min-w-0 p-5 sm:p-8"><p className="text-sm text-muted-foreground">Operations</p><h1 className="mb-8 font-display text-4xl font-semibold">{tabs.find(([id])=>id===tab)?.[1]}</h1>{notice&&<p className="mb-5 rounded-md bg-card p-3 text-sm" role="status">{notice}</p>}{loading?<p>Loading operations…</p>:<>
{tab==="inquiries"&&<div className="space-y-3">{inquiries.length?inquiries.map(q=><article key={q.id} className="rounded-md border border-border bg-card p-5"><div className="flex flex-wrap justify-between gap-3"><div><strong>{q.name}</strong><p className="text-sm text-muted-foreground">{q.email} · {q.company||"Independent"}</p></div><select value={q.status} onChange={e=>status("inquiries",q.id,e.target.value)} className="h-9 rounded-md border border-input bg-background px-2 text-sm"><option>new</option><option>reviewing</option><option>qualified</option><option>closed</option></select></div><p className="mt-3 whitespace-pre-wrap text-sm">{q.message}</p><p className="mt-3 text-xs text-muted-foreground">{q.service}{q.budget?` · ${q.budget}`:""}</p></article>):<Empty text="No inquiries yet."/>}</div>}
{tab==="clients"&&<div className="grid gap-3 lg:grid-cols-2">{clients.length?clients.map(c=><article key={c.id} className="rounded-md border border-border bg-card p-5"><strong>{c.company_name||"Unnamed client"}</strong><p className="mt-1 text-sm text-muted-foreground">{c.primary_contact||"No primary contact"}</p><p className="mt-4 whitespace-pre-wrap text-sm">{c.notes}</p></article>):<Empty text="No clients yet."/>}</div>}
{tab==="projects"&&<div className="grid gap-8 xl:grid-cols-[.7fr_1.3fr]"><form onSubmit={createProject} className="space-y-4"><h2 className="text-xl font-bold">New project</h2><div><Label htmlFor="client_id">Client</Label><select id="client_id" name="client_id" required className="mt-2 h-10 w-full rounded-md border border-input bg-background px-3"><option value="">Select a client</option>{clients.map(c=><option key={c.id} value={c.id}>{c.company_name||c.primary_contact||c.id}</option>)}</select></div><div><Label htmlFor="name">Project name</Label><Input id="name" name="name" required minLength={2} maxLength={120} className="mt-2"/></div><div><Label htmlFor="service">Service</Label><Input id="service" name="service" maxLength={100} className="mt-2"/></div><div><Label htmlFor="summary">Summary</Label><Textarea id="summary" name="summary" maxLength={1000} className="mt-2"/></div><Button>Create project</Button></form><div className="space-y-3">{projects.length?projects.map(p=><article key={p.id} className="rounded-md border border-border bg-card p-5"><div className="flex flex-wrap justify-between gap-3"><div><strong>{p.name}</strong><p className="text-sm text-muted-foreground">{p.service||"Service not set"} · {p.progress}%</p></div><select value={p.status} onChange={e=>status("projects",p.id,e.target.value)} className="h-9 rounded-md border border-input bg-background px-2 text-sm"><option>planned</option><option>active</option><option>paused</option><option>completed</option></select></div><p className="mt-3 text-sm">{p.summary}</p></article>):<Empty text="No projects yet."/>}</div></div>}
{tab==="tickets"&&<Rows items={tickets} empty="No support tickets." render={(t)=><div className="flex flex-wrap justify-between gap-3"><div><strong>{t.subject}</strong><p className="mt-1 max-w-2xl text-sm text-muted-foreground">{t.description}</p></div><select value={t.status} onChange={e=>status("tickets",t.id,e.target.value)} className="h-9 rounded-md border border-input bg-background px-2 text-sm"><option>open</option><option>in_progress</option><option>resolved</option><option>closed</option></select></div>}/>} 
{tab==="invoices"&&<Rows items={invoices} empty="No invoices yet." render={(i)=><div className="grid gap-2 sm:grid-cols-4"><strong>{i.invoice_number}</strong><span>{new Intl.NumberFormat("en-US",{style:"currency",currency:i.currency}).format(i.amount_cents/100)}</span><span>{i.due_date??"No due date"}</span><select value={i.status} onChange={e=>status("invoices",i.id,e.target.value)} className="h-9 rounded-md border border-input bg-background px-2 text-sm"><option>draft</option><option>sent</option><option>paid</option><option>overdue</option><option>void</option></select></div>}/>} 
{tab==="analytics"&&<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Open inquiries",inquiries.filter(i=>i.status!=="closed").length],["Active projects",projects.filter(p=>p.status==="active").length],["Open tickets",tickets.filter(t=>!['resolved','closed'].includes(t.status)).length],["Paid revenue",new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(revenue/100)]].map(([label,value])=><div key={label} className="rounded-md border border-border bg-card p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-3 font-display text-4xl font-semibold">{value}</p></div>)}</div>}
</>}</section></div></div>}
function Empty({text}:{text:string}){return <div className="rounded-md border border-dashed border-border p-10 text-center text-sm text-muted-foreground">{text}</div>}
function Rows<T extends {id:string}>({items,empty,render}:{items:T[];empty:string;render:(item:T)=>React.ReactNode}){return items.length?<div className="divide-y divide-border border-y border-border">{items.map(item=><div key={item.id} className="py-5">{render(item)}</div>)}</div>:<Empty text={empty}/>}