import { useEffect, useMemo, useState } from "react";
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { Download, FileText, FolderKanban, LifeBuoy, LogOut, Receipt, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { supabase } from "@/integrations/supabase/client";
import { pageMeta } from "@/lib/seo";
import type { Database } from "@/integrations/supabase/types";

type Project = Database["public"]["Tables"]["projects"]["Row"];
type Deliverable = Database["public"]["Tables"]["deliverables"]["Row"];
type Ticket = Database["public"]["Tables"]["tickets"]["Row"];
type Invoice = Database["public"]["Tables"]["invoices"]["Row"];
type Profile = Database["public"]["Tables"]["profiles"]["Row"];
type Tab = "projects"|"deliverables"|"support"|"invoices"|"profile";

export const Route = createFileRoute("/_authenticated/dashboard")({ head: () => pageMeta("Client workspace", "Track your TENURE AI projects, deliverables, support, and invoices."), component: Dashboard });

function Dashboard() {
  const navigate = useNavigate(); const { user } = Route.useRouteContext(); const [tab,setTab]=useState<Tab>("projects"); const [loading,setLoading]=useState(true); const [notice,setNotice]=useState("");
  const [projects,setProjects]=useState<Project[]>([]); const [deliverables,setDeliverables]=useState<Deliverable[]>([]); const [tickets,setTickets]=useState<Ticket[]>([]); const [invoices,setInvoices]=useState<Invoice[]>([]); const [profile,setProfile]=useState<Profile|null>(null); const [clientId,setClientId]=useState<string|null>(null);
  async function load() { setLoading(true); const [p,d,t,i,pr,c] = await Promise.all([supabase.from("projects").select("*").order("created_at",{ascending:false}),supabase.from("deliverables").select("*").order("created_at",{ascending:false}),supabase.from("tickets").select("*").order("created_at",{ascending:false}),supabase.from("invoices").select("*").order("created_at",{ascending:false}),supabase.from("profiles").select("*").eq("id",user.id).maybeSingle(),supabase.from("clients").select("id").eq("user_id",user.id).maybeSingle()]); setProjects(p.data??[]);setDeliverables(d.data??[]);setTickets(t.data??[]);setInvoices(i.data??[]);setProfile(pr.data);setClientId(c.data?.id??null);setLoading(false); }
  useEffect(()=>{ void load(); },[]);
  const projectNames=useMemo(()=>Object.fromEntries(projects.map(p=>[p.id,p.name])),[projects]);
  async function createTicket(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!clientId){setNotice("Your client workspace is not connected yet. Please contact the team.");return;}const fd=new FormData(e.currentTarget);const subject=String(fd.get("subject")??"").trim().replace(/[<>]/g,"").slice(0,120);const description=String(fd.get("description")??"").trim().replace(/[<>]/g,"").slice(0,2000);const priority=String(fd.get("priority")??"normal");if(subject.length<3||description.length<10)return;const {error}=await supabase.from("tickets").insert({client_id:clientId,created_by:user.id,subject,description,priority});if(error)setNotice(error.message);else{setNotice("Support request sent.");(e.currentTarget as HTMLFormElement).reset();await load();}}
  async function saveProfile(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const payload={display_name:String(fd.get("display_name")??"").trim().replace(/[<>]/g,"").slice(0,80),company:String(fd.get("company")??"").trim().replace(/[<>]/g,"").slice(0,120),job_title:String(fd.get("job_title")??"").trim().replace(/[<>]/g,"").slice(0,100)};const {error}=await supabase.from("profiles").update(payload).eq("id",user.id);setNotice(error?error.message:"Profile updated.");if(!error)await load();}
  async function download(path:string|null){if(!path)return;const {data,error}=await supabase.storage.from("deliverables").createSignedUrl(path,60);if(error)setNotice("This file is not available.");else window.open(data.signedUrl,"_blank","noopener,noreferrer");}
  const tabs:[Tab,string,typeof FolderKanban][]=[["projects","Projects",FolderKanban],["deliverables","Deliverables",FileText],["support","Support",LifeBuoy],["invoices","Invoices",Receipt],["profile","Profile",UserRound]];
  return <div className="min-h-[calc(100vh-72px)] bg-muted/50"><div className="mx-auto grid max-w-7xl md:grid-cols-[230px_1fr]"><aside className="border-b border-border p-5 md:min-h-[calc(100vh-72px)] md:border-b-0 md:border-r"><p className="text-xs font-bold uppercase text-accent">Client workspace</p><div className="mt-6 flex gap-2 overflow-x-auto md:flex-col">{tabs.map(([id,label,Icon])=><Button key={id} variant={tab===id?"secondary":"ghost"} className="justify-start" onClick={()=>setTab(id)}><Icon/>{label}</Button>)}</div><Button variant="ghost" className="mt-6 justify-start" onClick={async()=>{await supabase.auth.signOut();await navigate({to:"/auth"})}}><LogOut/>Sign out</Button></aside>
    <section className="min-w-0 p-5 sm:p-8"><div className="mb-8"><p className="text-sm text-muted-foreground">Welcome{profile?.display_name?`, ${profile.display_name}`:""}</p><h1 className="font-display text-4xl font-semibold">{tabs.find(([id])=>id===tab)?.[1]}</h1></div>{notice&&<p className="mb-5 rounded-md border border-border bg-card p-3 text-sm" role="status">{notice}</p>}{loading?<p>Loading workspace…</p>:<>
      {tab==="projects"&&(projects.length?<div className="grid gap-4 lg:grid-cols-2">{projects.map(p=><article key={p.id} className="rounded-md border border-border bg-card p-5"><div className="flex items-start justify-between gap-3"><h2 className="text-xl font-bold">{p.name}</h2><Badge variant="secondary">{p.status}</Badge></div><p className="mt-2 text-sm text-muted-foreground">{p.summary||"Project details will appear here."}</p><div className="mt-6 flex justify-between text-xs"><span>{p.stage}</span><span>{p.progress}%</span></div><Progress value={p.progress} className="mt-2"/></article>)}</div>:<Empty text="No projects yet. Once work begins, it will appear here."/>)}
      {tab==="deliverables"&&(deliverables.length?<div className="divide-y divide-border border-y border-border">{deliverables.map(d=><div key={d.id} className="flex flex-wrap items-center justify-between gap-4 py-5"><div><p className="font-bold">{d.title}</p><p className="text-sm text-muted-foreground">{projectNames[d.project_id]??"Project"} · v{d.version}</p></div><div className="flex items-center gap-2"><Badge variant="outline">{d.status}</Badge>{d.file_path&&<Button size="sm" variant="outline" onClick={()=>download(d.file_path)}><Download/>Download</Button>}</div></div>)}</div>:<Empty text="No deliverables have been shared yet."/>)}
      {tab==="support"&&<div className="grid gap-8 lg:grid-cols-[.9fr_1.1fr]"><form onSubmit={createTicket} className="space-y-4"><h2 className="text-xl font-bold">New request</h2><div><Label htmlFor="subject">Subject</Label><Input id="subject" name="subject" required minLength={3} maxLength={120} className="mt-2"/></div><div><Label htmlFor="description">What do you need?</Label><Textarea id="description" name="description" required minLength={10} maxLength={2000} className="mt-2 min-h-32"/></div><div><Label htmlFor="priority">Priority</Label><select id="priority" name="priority" className="mt-2 h-10 w-full rounded-md border border-input bg-background px-3"><option>normal</option><option>high</option><option>urgent</option></select></div><Button>Send request</Button></form><div><h2 className="mb-4 text-xl font-bold">Request history</h2>{tickets.length?<div className="space-y-3">{tickets.map(t=><article key={t.id} className="rounded-md border border-border bg-card p-4"><div className="flex justify-between gap-3"><strong>{t.subject}</strong><Badge variant="outline">{t.status.replace("_"," ")}</Badge></div><p className="mt-2 whitespace-pre-wrap text-sm text-muted-foreground">{t.description}</p></article>)}</div>:<Empty text="No support requests yet."/>}</div></div>}
      {tab==="invoices"&&(invoices.length?<div className="divide-y divide-border border-y border-border">{invoices.map(i=><div key={i.id} className="grid gap-2 py-5 sm:grid-cols-4"><strong>{i.invoice_number}</strong><span>{new Intl.NumberFormat("en-US",{style:"currency",currency:i.currency}).format(i.amount_cents/100)}</span><span className="text-muted-foreground">{i.due_date??"No due date"}</span><Badge variant="outline" className="w-fit">{i.status}</Badge></div>)}</div>:<Empty text="No invoices yet."/>)}
      {tab==="profile"&&<form onSubmit={saveProfile} className="max-w-xl space-y-4"><div><Label htmlFor="display_name">Display name</Label><Input id="display_name" name="display_name" defaultValue={profile?.display_name??""} maxLength={80} className="mt-2"/></div><div><Label htmlFor="company">Company</Label><Input id="company" name="company" defaultValue={profile?.company??""} maxLength={120} className="mt-2"/></div><div><Label htmlFor="job_title">Job title</Label><Input id="job_title" name="job_title" defaultValue={profile?.job_title??""} maxLength={100} className="mt-2"/></div><Button>Save profile</Button></form>}
    </>}</section></div></div>;
}
function Empty({text}:{text:string}){return <div className="rounded-md border border-dashed border-border p-10 text-center text-sm text-muted-foreground">{text}</div>}