CREATE SCHEMA IF NOT EXISTS private;
REVOKE ALL ON FUNCTION public.set_updated_at() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.has_role(uuid, public.app_role) FROM PUBLIC, anon;
ALTER FUNCTION public.has_role(uuid, public.app_role) SET SCHEMA private;
GRANT USAGE ON SCHEMA private TO authenticated;
GRANT EXECUTE ON FUNCTION private.has_role(uuid, public.app_role) TO authenticated;

DROP POLICY "profiles_self_read" ON public.profiles;
CREATE POLICY "profiles_self_read" ON public.profiles FOR SELECT TO authenticated USING (id = auth.uid() OR private.has_role(auth.uid(), 'admin'));
DROP POLICY "profiles_self_update" ON public.profiles;
CREATE POLICY "profiles_self_update" ON public.profiles FOR UPDATE TO authenticated USING (id = auth.uid() OR private.has_role(auth.uid(), 'admin')) WITH CHECK (id = auth.uid() OR private.has_role(auth.uid(), 'admin'));
DROP POLICY "roles_self_read" ON public.user_roles;
CREATE POLICY "roles_self_read" ON public.user_roles FOR SELECT TO authenticated USING (user_id = auth.uid() OR private.has_role(auth.uid(), 'admin'));
DROP POLICY "admins_manage_inquiries" ON public.inquiries;
CREATE POLICY "admins_manage_inquiries" ON public.inquiries FOR ALL TO authenticated USING (private.has_role(auth.uid(), 'admin')) WITH CHECK (private.has_role(auth.uid(), 'admin'));
DROP POLICY "clients_self_read" ON public.clients;
CREATE POLICY "clients_self_read" ON public.clients FOR SELECT TO authenticated USING (user_id = auth.uid() OR private.has_role(auth.uid(), 'admin'));
DROP POLICY "admins_manage_clients" ON public.clients;
CREATE POLICY "admins_manage_clients" ON public.clients FOR ALL TO authenticated USING (private.has_role(auth.uid(), 'admin')) WITH CHECK (private.has_role(auth.uid(), 'admin'));
DROP POLICY "project_access" ON public.projects;
CREATE POLICY "project_access" ON public.projects FOR SELECT TO authenticated USING (private.has_role(auth.uid(), 'admin') OR EXISTS (SELECT 1 FROM public.clients c WHERE c.id = client_id AND c.user_id = auth.uid()));
DROP POLICY "admins_manage_projects" ON public.projects;
CREATE POLICY "admins_manage_projects" ON public.projects FOR ALL TO authenticated USING (private.has_role(auth.uid(), 'admin')) WITH CHECK (private.has_role(auth.uid(), 'admin'));
DROP POLICY "milestone_access" ON public.milestones;
CREATE POLICY "milestone_access" ON public.milestones FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.projects p JOIN public.clients c ON c.id=p.client_id WHERE p.id=project_id AND (c.user_id=auth.uid() OR private.has_role(auth.uid(),'admin'))));
DROP POLICY "admins_manage_milestones" ON public.milestones;
CREATE POLICY "admins_manage_milestones" ON public.milestones FOR ALL TO authenticated USING (private.has_role(auth.uid(),'admin')) WITH CHECK (private.has_role(auth.uid(),'admin'));
DROP POLICY "deliverable_access" ON public.deliverables;
CREATE POLICY "deliverable_access" ON public.deliverables FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.projects p JOIN public.clients c ON c.id=p.client_id WHERE p.id=project_id AND (c.user_id=auth.uid() OR private.has_role(auth.uid(),'admin'))));
DROP POLICY "admins_manage_deliverables" ON public.deliverables;
CREATE POLICY "admins_manage_deliverables" ON public.deliverables FOR ALL TO authenticated USING (private.has_role(auth.uid(),'admin')) WITH CHECK (private.has_role(auth.uid(),'admin'));
DROP POLICY "ticket_access" ON public.tickets;
CREATE POLICY "ticket_access" ON public.tickets FOR SELECT TO authenticated USING (private.has_role(auth.uid(),'admin') OR EXISTS (SELECT 1 FROM public.clients c WHERE c.id=client_id AND c.user_id=auth.uid()));
DROP POLICY "clients_create_tickets" ON public.tickets;
CREATE POLICY "clients_create_tickets" ON public.tickets FOR INSERT TO authenticated WITH CHECK ((created_by=auth.uid() AND EXISTS (SELECT 1 FROM public.clients c WHERE c.id=client_id AND c.user_id=auth.uid())) OR private.has_role(auth.uid(),'admin'));
DROP POLICY "admins_manage_tickets" ON public.tickets;
CREATE POLICY "admins_manage_tickets" ON public.tickets FOR ALL TO authenticated USING (private.has_role(auth.uid(),'admin')) WITH CHECK (private.has_role(auth.uid(),'admin'));
DROP POLICY "message_access" ON public.ticket_messages;
CREATE POLICY "message_access" ON public.ticket_messages FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.tickets t JOIN public.clients c ON c.id=t.client_id WHERE t.id=ticket_id AND (c.user_id=auth.uid() OR private.has_role(auth.uid(),'admin'))));
DROP POLICY "message_create" ON public.ticket_messages;
CREATE POLICY "message_create" ON public.ticket_messages FOR INSERT TO authenticated WITH CHECK (author_id=auth.uid() AND EXISTS (SELECT 1 FROM public.tickets t JOIN public.clients c ON c.id=t.client_id WHERE t.id=ticket_id AND (c.user_id=auth.uid() OR private.has_role(auth.uid(),'admin'))));
DROP POLICY "invoice_access" ON public.invoices;
CREATE POLICY "invoice_access" ON public.invoices FOR SELECT TO authenticated USING (private.has_role(auth.uid(),'admin') OR EXISTS (SELECT 1 FROM public.clients c WHERE c.id=client_id AND c.user_id=auth.uid()));
DROP POLICY "admins_manage_invoices" ON public.invoices;
CREATE POLICY "admins_manage_invoices" ON public.invoices FOR ALL TO authenticated USING (private.has_role(auth.uid(),'admin')) WITH CHECK (private.has_role(auth.uid(),'admin'));